kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tl500-teamsters.fullname" . }}
  namespace: {{ .Values.tl500Namespace | default "tl500" }}
  labels:
    {{- include "tl500-teamsters.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tl500-teamsters.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
