apiVersion: v1
stringData:
  CLUSTER_DOMAIN: {{ .Values.clusterDomain | quote }}
  FORCE_HTTPS: {{ .Values.forceHttps | quote }}
  GIT_SERVER: {{ .Values.gitServer | quote }}
  GITLAB_PASSWORD: {{ .Values.gitlabPassword | quote }}
  GITLAB_USER: {{ .Values.gitlabUser }}
  OCP_ADMIN_PASSWORD: {{ .Values.ocpAdminPassword }}
  OCP_ADMIN_USER: {{ .Values.ocpAdminUser }}
kind: Secret
metadata:
  name: {{ include "tl500-teamsters.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tl500-teamsters.labels" . | nindent 4 }}
type: Opaque
